### ISSUE TITLE
Not compatible with React 16

### ISSUE THREAD

**Issue by frazboyz** [mukeshsoni/react-telephone-input#143] opened 2017-08-11 00:29 UTC
In React 16, they have removed React.createClass which breaks this library.

**Comment by Si1kIfY** [comment] 2017-08-17 12:33
Related to my issue #136

**Comment by satishnath** [comment] 2017-09-14 22:21
I see that react-onclickoutside dependency has to updated, the newer version of the library have the necessary updates to make it React (16) complaint.

**Comment by mukeshsoni** [comment] 2017-09-15 04:28
@frazboyz @Si1kIfY @satishnath I have updated the `react-onclickoutside` library to latest in v4.2.2.

**Comment by mukeshsoni** [comment] 2017-09-15 04:37
Duplicate of #136

**Closed by mukeshsoni** 2017-09-15 04:37 UTC

**Comment by satishnath** [comment] 2017-09-15 13:31
Thank you so much for the library!
