### ISSUE TITLE
not able to select Kazakhstan flag

### ISSUE THREAD

**Issue by Infinity1high** [mukeshsoni/react-telephone-input#182] opened 2018-07-03 17:02 UTC
As Kazakhstan country code has value '+7'  , the same as Russian country code, it is not possible to select kazakhstan's flag.
Actually country code is +77

**Comment by mukeshsoni** [comment] 2018-07-04 00:58
Will take a look. Thanks for reporting!

**Comment by mukeshsoni** [comment] 2018-08-26 15:16
@Infinity1high I could not reproduce the error. Maybe fixed in 4.73.0

**Closed** 2019-01-16 03:49 UTC
